### ISSUE TITLE
Clarification: Can aliases be further refined?

### ISSUE THREAD

**Issue by ohpauleez** [liquid-rust/flux#146] opened 2022-09-22 18:19 UTC
First off-  Thanks for this effort!  I've been having a blast working through the code and attempting to port parts of the [CBCAST](https://github.com/lsd-ucsc/cbcast-lh) stuff.

I'm curious if the following is intended behavior or user error.
Given:

```rust
#[flux::alias(type PrimeU32() = u32)]
type PrimeU32 = u32;

#[flux::constant]
const MAX_SMALL_PRIME: PrimeU32 = 97; 

#[flux::sig(fn(x: u32) -> PrimeU32{ v: v <= MAX_SMALL_PRIME })] 
pub fn a_prime(x: u32) -> PrimeU32 {
    MAX_SMALL_PRIME
}
```

The following error is reported:

```
error[FLUX]: cannot resolve `PrimeU32`
  --> /home/paul/scratch/rusttest/ver-causal/src/scratch.rs:45:27
   |
45 | #[flux::sig(fn(x: u32) -> PrimeU32{ v: v <= MAX_SMALL_PRIME })]
   |                           ^^^^^^^^

error: aborting due to previous error
```

**Comment by ranjitjhala** [comment] 2022-09-22 18:29
We _should_ allow this, but I believe ATM it is not supported :-(

**Comment by nilehmann** [comment] 2022-09-23 04:08
I think in this case the issue is simpler because there's no real refinement in the alias so it shouldn't even require the `flux::alias` annotation. I'm currently working on a refactor for name resolving which I think should fix this particular issue. As for further refining aliases, we should definitly support it but that would require extra work. I'm thinking something like


```rust
#[flux::alias(type Nat() = i32{v : v >= 0)]
type Nat = i32;

#[flux::sig(fn(x: Nat{v : v < 10})) -> ()] {
     ...
}
```

**Comment by nilehmann** [comment] 2023-01-27 19:11
Aliases 2.0 can be further refined so I'm closing this.

**Closed by nilehmann** 2023-01-27 19:11 UTC
Labels: enhancement, good first issue, error-messages

**Comment by ranjitjhala** [comment] 2023-01-27 19:22
super!
